### ISSUE TITLE
unimplemented abstract method

### ISSUE THREAD

**Issue by JosephXu01** [jdcloud-api/jdcloud-sdk-java#22]
oss 下面的 OssClient 继承了 core 里面的抽象类 JdcloudClient，  但是没有实现里面的抽象方法getRegionId(),  这样就导致在类 JdcloudExecutor 里面的方法 execute（）  执行到 jdcloudClient.getRegionId() 的时候产生异常。

**Comment by lixuenan2333** [comment]
JdcloudClient 在1.0.3以后的版本才有getRegionId()，目前该版本还处于内测当中，未对外开放，github上引用的core应该都是1.0.0或1.0.1，请问你是从哪看到带有getRegionId()的JdcloudClient代码？

**Comment by JosephXu01** [comment]
http://mvnrepository.com/artifact/com.jdcloud.sdk/core

Maven 库上有1.0.3的。 那么我还是用低版本的？

**Comment by JosephXu01** [comment]
看来oss 目前对应 core 1.0.0版本。
